In [14]:
a = [1,2,3,4]
b = [2,3,4,5]
# 2 hücreyi çalıştır dersek arka arkaya, bize sadece son çalıştırılan hücreyi verir
#a
#b

In [15]:
ab =[] 

for i in range(0,len(a)):
    ab.append(a[i] * b[i])
ab

[2, 6, 12, 20]

In [16]:
import numpy as np

In [17]:
a = np.array([1,2,3,4])
b = np.array([2,5,6,8])

In [18]:
a*b

array([ 2, 10, 18, 32])

In [20]:
np.array([3.14,4,12,3])
np.array([3.14,4,5,6,7] , dtype = "int")

array([3, 4, 5, 6, 7])

In [21]:
#Sıfırdan array oluşturma

In [24]:
np.zeros(10, dtype = int )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones((3,5) , dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.full((3,5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [27]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [29]:
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [30]:
np.random.normal(10,4,(3,4))

# Ortalaması= 10, stds = 4
# Tek boyutlu array vektör, 2D matrix

array([[ 5.01039614,  8.86916089, 16.21425821,  6.4780825 ],
       [ 7.5480646 , 11.31837928,  9.99350117, 12.23098653],
       [ 7.1640051 ,  9.76927522, 14.75816599,  7.44491266]])

In [31]:
np.random.randint(0,10, (3,3))

array([[0, 8, 3],
       [3, 5, 2],
       [0, 9, 9]])

- ndim: Boyut sayısı
- shape: Boyut bilgisi
- size: Toplam eleman sayısı
- dtype: Array veri tipi
- **kalın** 
- _italik_

In [35]:
np.random.randint(10, size = 10)

array([6, 0, 5, 6, 9, 7, 0, 2, 4, 3])

In [41]:
a = np.random.randint(10, size = 10)

In [42]:
a.ndim

1

In [43]:
a.dtype

dtype('int64')

In [44]:
a.size

10

In [45]:
a.shape

(10,)

In [47]:
b = np.random.randint(10, size =(3,5))

In [48]:
b

array([[0, 6, 2, 5, 6],
       [7, 9, 2, 5, 6],
       [1, 6, 2, 7, 5]])

In [49]:
b.ndim

2

In [50]:
b.shape

(3, 5)

In [51]:
b.dtype

dtype('int64')

In [52]:
b.size

15

# Yeniden Şekillendirme (reshaping)

In [54]:
import numpy as np

In [55]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a = np.arange(1,10)

In [60]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#tek boyutlu array = vektör
#iki boyutlu array = matrix

In [61]:
a.ndim

1

In [67]:
b = a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
b.ndim

2

# Array Birleştirme (Concatenation)

In [3]:
import numpy as np

In [72]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [73]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [80]:
z = np.array([7,8,9])

In [81]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
#iki boyut

In [4]:
#iki boyutlu array oluşturmak için iki tane köşeli parantez kullanıyoruz.
a = np.array([[1,2,3],
             [4,5,6]])

In [76]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Arrayleri ayırma (Splitting)

In [82]:
#n indexe karşılık n+1 ayırma işlemi yapılır.

In [3]:
import numpy as np

In [7]:
x = np.array([1,2,3,99,99,3,2,1])

In [5]:
np.split(x, [3,5])


[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [5]:
# 2 tane index verdik 3 işlem yapılıyor, 3 tane index verseydik aralık olarak 4 tane işlem yapılırdı.
# n indexe karşılık n+1 ayırma işlemi yapılır.

In [9]:
# a,b,c direkt 3 çıktıya atanır. Diğer birçok python işlemi için gerçekleştirilebilir
a,b,c = np.split(x, [3,5])

In [8]:
a

array([1, 2, 3])

In [9]:
b

array([99, 99])

In [10]:
c

array([3, 2, 1])

In [11]:
#iki boyutlu ayırma

In [12]:
# Tek boyutlu bir arrayi .reshape ile 2 boyutlu hale getirebiliyoruz.
m = np.arange(16).reshape(4,4)

In [13]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
# 2. satıra kadar 'e kadar devam etmektedir. 
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [15]:
ust,alt = np.vsplit(m,[2])

In [17]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
# 2. sütuna kadar 'e kadar devam etmektedir. 
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [22]:
sag, sol = np.hsplit(m,[2])

In [23]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [24]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [19]:
import numpy as np

In [20]:
v = np.array([2,1,4,3,5,6])

In [21]:
v

array([2, 1, 4, 3, 5, 6])

In [22]:
#sort metodu (fonksiyonunu kullanıyoruz)
# numpy'ın içinden çağırılınca sort metodu ifadeyi bozmadı.
np.sort(v)

array([1, 2, 3, 4, 5, 6])

In [23]:
#Numpy içinden çağırıldığı için sort metodu ifademizin yapısı bozmadı
v

array([2, 1, 4, 3, 5, 6])

In [24]:
# Burada sort ifadesi yapıyı bozmuştur
v.sort()

In [32]:
v

array([1, 2, 3, 4, 5, 6])

In [37]:
# NumPy içinde .sort metodu çağrılırsa veri setini bozmadığı gözlenmiştir. 
# Eğer ayrı bir fonksiyon olarak çağırılırsa, (yeniden atama) komple değişiklik yaşanır.

In [38]:
# İki boyutlu array sıralama

In [43]:
m = np.random.normal(20,5, (3,3))

m

In [26]:
# Axis = 1 dediğimiz için vertical olarak (x ekseninde - yatayda küçükten büyüğe sıralanmıştır)
np.sort(m, axis = 1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
# Axis = 0 dediğimiz için horizontal olarak (y ekseninde - dikey küçükten büyüğe sıralanmıştır)
np.sort(m, axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Index ile Elemanlara Erişmek

In [46]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([1, 7, 0, 2, 2, 8, 7, 1, 7, 3])

In [47]:
a[0]

1

In [48]:
a[-1]

3

In [49]:
 a[0] = 41

In [50]:
a

array([41,  7,  0,  2,  2,  8,  7,  1,  7,  3])

In [51]:
#iki boyutlu array üzerinden elemana ulaşmak

In [27]:
# m = np.random.randint(10, size = 10) dersek bu şekilde tek boyutlu bir array oluşturmuş oluyoruz.

m = np.random.randint(10, size = (3,5))
m

array([[6, 4, 2, 9, 4],
       [3, 5, 9, 9, 7],
       [3, 1, 6, 8, 5]])

In [54]:
m[0,0]

7

In [55]:
m[1,1]

4

In [56]:
m[2,3]

8

In [57]:
m[1,4] = 99

In [58]:
m

array([[ 7,  2,  9,  6,  4],
       [ 9,  4,  9,  8, 99],
       [ 1,  1,  8,  8,  5]])

In [59]:
m[1,4] = 9.9

In [60]:
m

array([[7, 2, 9, 6, 4],
       [9, 4, 9, 8, 9],
       [1, 1, 8, 8, 5]])

In [61]:
# oluşturma sırasında içerisinde 1 tane ondalık değer varsa tüm arrayin tipi ondalık olarak görülüyor.
#en baştan oluşturma işlemi değil sonrasında eklenmeye çalışılıyorsa o zaman olmuyor.

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [62]:
import numpy as np

In [63]:
a = np.arange(20,30)

In [64]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [65]:
a[0:3]

array([20, 21, 22])

In [66]:
a[:3]

array([20, 21, 22])

In [67]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [68]:
a[1::2]

array([21, 23, 25, 27, 29])

In [69]:
a[::2]

array([20, 22, 24, 26, 28])

In [70]:
a[0::3]

array([20, 23, 26, 29])

In [71]:
#iki boyutlu slice işlemleri

In [72]:
m = np.random.randint(10, size = (5,5))

In [73]:
m

array([[7, 9, 5, 3, 5],
       [0, 9, 7, 4, 5],
       [1, 8, 5, 7, 0],
       [6, 1, 5, 7, 2],
       [4, 9, 4, 8, 8]])

In [74]:
m[:,0]

array([7, 0, 1, 6, 4])

In [75]:
m[:,1]

array([9, 9, 8, 1, 9])

In [76]:
m[:,4]

array([5, 5, 0, 2, 8])

In [77]:
m

array([[7, 9, 5, 3, 5],
       [0, 9, 7, 4, 5],
       [1, 8, 5, 7, 0],
       [6, 1, 5, 7, 2],
       [4, 9, 4, 8, 8]])

In [78]:
m[0,:]

array([7, 9, 5, 3, 5])

In [83]:
m[1,:]

array([0, 9, 7, 4, 5])

In [84]:
m[0:2,0:3]

array([[7, 9, 5],
       [0, 9, 7]])

In [86]:
m[:,:2]
#tüm satırları al , 0 dan başlayıp 2.sütüna kadar al

array([[7, 9],
       [0, 9],
       [1, 8],
       [6, 1],
       [4, 9]])

In [88]:
m

array([[7, 9, 5, 3, 5],
       [0, 9, 7, 4, 5],
       [1, 8, 5, 7, 0],
       [6, 1, 5, 7, 2],
       [4, 9, 4, 8, 8]])

In [87]:
m[1:3,:2]

array([[0, 9],
       [1, 8]])

In [90]:
import numpy as np
a = np.random.randint(10 , size = (5,5))
a

array([[1, 4, 7, 5, 8],
       [7, 4, 5, 0, 7],
       [5, 0, 6, 5, 4],
       [9, 2, 5, 4, 4],
       [2, 8, 5, 9, 3]])

In [92]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 4],
       [7, 4],
       [5, 0]])

In [97]:
alt_a[0,0] = 99
alt_a[1,1] = 88

In [98]:
alt_a

array([[99,  4],
       [ 7, 88],
       [ 5,  0]])

In [99]:
a

array([[99,  4,  7,  5,  8],
       [ 7, 88,  5,  0,  7],
       [ 5,  0,  6,  5,  4],
       [ 9,  2,  5,  4,  4],
       [ 2,  8,  5,  9,  3]])

In [105]:
m = np.random.randint(10, size =(5,5))
m

array([[1, 3, 3, 2, 1],
       [4, 6, 6, 6, 0],
       [6, 8, 0, 7, 0],
       [1, 0, 7, 4, 8],
       [0, 8, 8, 1, 8]])

In [106]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[1, 3],
       [4, 6],
       [6, 8]])

In [107]:
alt_b[0,0] = 999

In [108]:
alt_b

array([[999,   3],
       [  4,   6],
       [  6,   8]])

In [109]:
m

array([[1, 3, 3, 2, 1],
       [4, 6, 6, 6, 0],
       [6, 8, 0, 7, 0],
       [1, 0, 7, 4, 8],
       [0, 8, 8, 1, 8]])

# Fancy Index ile Elemanlara Erişmek

In [110]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [115]:
v[1]

3

In [116]:
[v[1], v[4],v[5]]

[3, 12, 15]

In [118]:
al_getir = [1,3,5,7]

In [119]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [120]:
v[al_getir]

array([ 3,  9, 15, 21])

In [121]:
#iki boyutta fancy

In [122]:
m = np.arange(9).reshape((3,3))

In [123]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
satir = np.array([0,1])
sutun = np.array([1,2])

array([1, 2])

In [127]:
m[satir , sutun]

array([1, 5])

In [129]:
#basit index ile fancy index

In [130]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
m[0,[1,2]]

array([1, 2])

In [146]:
#slice ile fancy

In [147]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [150]:
import numpy as np
v = np.array([1,2,3,4,5,6])

In [153]:
v < 5

array([ True,  True,  True,  True, False, False])

In [155]:
v[v < 5]

array([1, 2, 3, 4])

In [156]:
v[v > 5]

array([6])

In [157]:
v[v == 5]

array([5])

In [159]:
v[v <= 5]

array([1, 2, 3, 4, 5])

In [160]:
v[v >= 5]

array([5, 6])

In [161]:
v[v != 5]

array([1, 2, 3, 4, 6])

In [162]:
v * 2

array([ 2,  4,  6,  8, 10, 12])

In [163]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [164]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [166]:
v ** 2
#kare alma 

array([ 1,  4,  9, 16, 25, 36])

# Matematiksel İşlemler

In [167]:
v - 1

array([0, 1, 2, 3, 4, 5])

In [168]:
v * 5 

array([ 5, 10, 15, 20, 25, 30])

In [169]:
v / 5 

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [173]:
v

array([1, 2, 3, 4, 5, 6])

In [170]:
#ufunc

In [171]:
np.subtract(v,1)

array([0, 1, 2, 3, 4, 5])

In [172]:
np.add(v,1)

array([2, 3, 4, 5, 6, 7])

In [174]:
np.multiply(v,5)

array([ 5, 10, 15, 20, 25, 30])

In [175]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [176]:
np.power(v,3)

array([  1,   8,  27,  64, 125, 216])

In [178]:
v % 2
np.mod(v,2)

array([1, 0, 1, 0, 1, 0])

In [179]:
np.absolute([np.array([-4])])

array([[4]])

In [180]:
np.sin(180)

-0.8011526357338306

In [181]:
np.cos(270)

0.9843819506325049

In [182]:
v = np.array([1,2,3])

In [183]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [184]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [185]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [186]:
?np

Type:        module
String form: <module 'numpy' from '/Users/yusufbayindir/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
File:        ~/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  

In [207]:
#Cheatsheet kullanmayı ve google ile bilmediğimizi araştırmayı öğrenmeliyiz.

# NumPy ile iki bilinmeyenli Denklem çözümü

In [208]:
import numpy as np

5 * x0 + x1 = 12

x0 + 3*x1 =10

In [211]:
a = np.array([[5,1] , [1,3]])
b = np.array([12,10])

In [212]:
a

array([[5, 1],
       [1, 3]])

In [213]:
b

array([12, 10])

In [215]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])